version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        depends_on:
            - nginx

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
