FROM apache/airflow:2.10.4

USER root

# Install necessary dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Set Airflow home
ENV AIRFLOW_HOME=/opt/airflow

# Expose Airflow Webserver port
EXPOSE 8080

# Default command to start Airflow
CMD ["bash", "-c", "airflow db upgrade && airflow scheduler & airflow webserver"]

# FROM apache/airflow:2.10.4

# # Install any additional dependencies you might need
# USER root
# RUN apt-get update \
#   && apt-get install -y --no-install-recommends \
#          vim \
#   && apt-get autoremove -yqq --purge \
#   && apt-get clean \
#   && rm -rf /var/lib/apt/lists/*

# # Create the 'airflow' user if it doesn't exist
# RUN useradd -m airflow

# # Switch to the 'airflow' user
# USER airflow

# # Ensure Airflow is installed
# RUN pip install apache-airflow

# # Set environment variables for Airflow
# ENV AIRFLOW_HOME=/opt/airflow

# # Expose ports for the webserver
# EXPOSE 8080

# CMD ["bash", "-c", "airflow db upgrade && airflow scheduler & airflow webserver"]


